name:                hb-word-ladder
version:             0.1.0.0
github:              "thktomska/hb-word-ladder"
license:             BSD3
author:              "thktomska"
maintainer:          "thktomska@gmail.com"
copyright:           "CC-0"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thktomska/hb-word-ladder#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
    - src/

executables:
  hb-word-ladder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hb-word-ladder

tests:
  hb-word-ladder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hb-word-ladder
